# Generated by Django 5.0.2 on 2024-02-24 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroommodel',
            options={'verbose_name': 'Общий чат', 'verbose_name_plural': 'Общие чаты'},
        ),
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='userchatroommodel',
            options={'verbose_name': 'Связь общих чатов и пользователей', 'verbose_name_plural': 'Связь общих чатов и пользователей'},
        ),
        migrations.CreateModel(
            name='ChatRoomInvitationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Waiting Acceptance/Discard', 'Ожидает подтверждения/отказа'), ('Accepted', 'Приглашение принято'), ('Discarded', 'Приглашение отклонено')], max_length=30, verbose_name='Статус приглашения')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to=settings.AUTH_USER_MODEL, verbose_name='Приглашаемый пользователь')),
                ('inviting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший пользователь')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.chatroommodel', verbose_name='Чат')),
            ],
        ),
    ]
