# Generated by Django 5.0.2 on 2024-02-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_alter_chatroommodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroominvitationmodel',
            options={'verbose_name': 'Приглашение на вступление в чат', 'verbose_name_plural': 'Приглашения на вступление в чат'},
        ),
    ]
