# Generated by Django 5.0.2 on 2024-02-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_chatroominvitationmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroominvitationmodel',
            name='status',
        ),
    ]
