# Generated by Django 5.0.2 on 2024-02-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='src_avatar',
            field=models.ImageField(upload_to='avatars/%Y-%m', verbose_name='Аватар'),
        ),
    ]
