# Generated by Django 5.0.2 on 2024-02-17 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(verbose_name='Роль пользователя')),
            ],
            options={
                'verbose_name': 'Роли пользователей',
                'verbose_name_plural': 'Роли пользователей',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='Роль пользователя',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication_app.userrolemodel'),
        ),
    ]
