# Generated by Django 5.0.2 on 2024-02-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_alter_customuser_src_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified_email',
            field=models.BooleanField(default=False, verbose_name='Is Verified Email'),
        ),
    ]
