# Generated by Django 5.0.2 on 2024-02-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0003_customuser_is_verified_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Accountant', 'Бухгалтер'), ('Editor', 'Редактор'), ('Admin', 'Администратор')], default='Admin', verbose_name='Роль пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified_email',
            field=models.BooleanField(default=False, verbose_name='Верифицирован ли Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Логин'),
        ),
    ]
