# Generated by Django 5.0.2 on 2024-02-17 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0004_alter_userrolemodel_role_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRoleModel',
            new_name='UserPositionModel',
        ),
        migrations.AlterModelOptions(
            name='userpositionmodel',
            options={'verbose_name_plural': 'Должности'},
        ),
        migrations.RenameField(
            model_name='userpositionmodel',
            old_name='role_name',
            new_name='position_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='position_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authentication_app.userpositionmodel', verbose_name='Роль пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Accountant', 'Бухгалтер'), ('Editor', 'Редактор'), ('Admin', 'Администратор')], default='admin', max_length=255, verbose_name='Роль пользователя'),
            preserve_default=False,
        ),
    ]
