# Generated by Django 5.0.2 on 2024-02-27 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0007_alter_customuser_position_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность (timezone)'),
        ),
    ]
