# Generated by Django 5.0.2 on 2024-02-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0008_customuser_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='Онлайн'),
            preserve_default=False,
        ),
    ]
