# Generated by Django 5.0.2 on 2024-02-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0009_customuser_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн'),
        ),
    ]
